let HEROES=[],DATA=[],lang='en';const $=x=>document.getElementById(x);const modeLabels={'arena':'Arena','expedition':'Expedition','castle-defense':'Castle Defense','castle-attack':'Castle Attack','bear':'Bear Hunt'};
const ar={introText:'تحليل جميع أبطال الجيل الأول إلى السابع باستخدام المهارات الفعلية وتأثيرات Expedition والإحصائيات والسلاح الشخصي.'};
Promise.all([fetch('heroes.json').then(r=>r.json()),fetch('hero-analysis.json').then(r=>r.json())]).then(([h,d])=>{HEROES=h;DATA=d;$('heroCount').textContent=h.length;fill();$('loading').textContent='Choose a hero and press Analyze Matchup.'}).catch(()=>{$('loading').innerHTML='Could not load JSON locally in this browser. Run from GitHub/Netlify or a local web server.'});
function fill(){HEROES.sort((a,b)=>a.generation-b.generation||a.name.localeCompare(b.name)).forEach(h=>{let o=document.createElement('option');o.value=h.id;o.textContent=`G${h.generation} · ${h.name} · ${h.class}`;$('hero').appendChild(o)})}
function A(id){return DATA.find(x=>x.id===id)}function H(id){return HEROES.find(x=>x.id===id)}
function scoreCounter(target,cand,mode){let s=48;const te=new Set(target.effects),ce=new Set(cand.effects);if(te.has('damage_buff')&&ce.has('damage_reduction'))s+=14;if(te.has('attack_buff')&&ce.has('enemy_attack_down'))s+=12;if(target.defense>65&&(ce.has('enemy_defense_down')||ce.has('enemy_damage_taken')))s+=13;if(target.offense>70&&(cand.defense>70||ce.has('shield')||ce.has('healing')))s+=12;if(te.has('healing')&&ce.has('enemy_damage_taken'))s+=5;if(cand.control>0&&!te.has('control'))s+=8;if(H(target.id).class!==H(cand.id).class)s+=3;s+=(cand.modes[mode]-target.modes[mode])*.12;return Math.max(40,Math.min(98,Math.round(s)))}
function scoreSynergy(target,cand,mode){let s=45;const t=new Set(target.effects),c=new Set(cand.effects);if(target.offense>target.defense&&cand.defense>65)s+=14;if(target.defense>=target.offense&&cand.offense>65)s+=13;if(c.has('healing')||c.has('shield')||c.has('damage_reduction'))s+=8;if(c.has('attack_buff')||c.has('lethality_buff')||c.has('enemy_damage_taken'))s+=8;if(t.has('control')&&cand.offense>65)s+=7;if(H(target.id).class!==H(cand.id).class)s+=5;s+=(cand.modes[mode]+target.modes[mode]-120)*.08;return Math.max(42,Math.min(98,Math.round(s)))}
function rankHTML(list){return list.map((x,i)=>{let h=H(x.id),a=A(x.id);return `<div class="rank"><span>0${i+1}</span><img src="${h.image}"><div><strong>${h.name}</strong><small>G${h.generation} · ${h.class} · ${a.role}</small></div><b>${x.score}%</b></div>`}).join('')}
function analyze(){let h=H($('hero').value),a=A(h.id),m=$('mode').value;if(!h)return;$('loading').hidden=true;$('results').hidden=false;$('heroImg').src=h.image;$('heroName').textContent=h.name;$('gen').textContent=`GENERATION ${h.generation}`;$('class').textContent=h.class;$('rarity').textContent=h.rarity;$('role').textContent=a.role;$('overview').textContent=h.overview;$('confidence').textContent=a.confidence+'%';$('confBar').style.width=a.confidence+'%';[['offense','offBar'],['defense','defBar'],['support','supBar']].forEach(([k,b])=>{$(k).textContent=a[k];$(b).style.width=a[k]+'%'});$('modeScore').textContent=a.modes[m];$('modeBar').style.width=a.modes[m]+'%';$('modeName').textContent=modeLabels[m];
let counters=DATA.filter(x=>x.id!==a.id).map(x=>({id:x.id,score:scoreCounter(a,x,m)})).sort((x,y)=>y.score-x.score).slice(0,5);let syn=DATA.filter(x=>x.id!==a.id).map(x=>({id:x.id,score:scoreSynergy(a,x,m)})).sort((x,y)=>y.score-x.score).slice(0,5);$('counters').innerHTML=rankHTML(counters);$('synergies').innerHTML=rankHTML(syn);let team=[{id:a.id,score:100},...syn.slice(0,2)];$('team').innerHTML='<div class="teamHeroes">'+team.map(x=>{let q=H(x.id),z=A(x.id);return `<div class="teamHero"><img src="${q.image}"><b>${q.name}</b><small>${q.class} · ${z.role}</small></div>`}).join('')+'</div>';$('teamReason').textContent=`Built for ${modeLabels[m]} by balancing ${a.role.toLowerCase()} value with the two highest complementary skill profiles.`;$('strengths').innerHTML=a.strengths.map(x=>`<span>${x}</span>`).join('');$('weaknesses').innerHTML=a.weaknesses.map(x=>`<span>${x}</span>`).join('');$('skills').innerHTML=[['Conquest',h.conquest],['Expedition',h.expedition],['Exclusive Gear',h.gear]].map(([n,v])=>`<div class="skillGroup"><h4>${n}</h4>${v.map(x=>`<p>${x}</p>`).join('')}</div>`).join('');window.scrollTo({top:$('results').offsetTop-15,behavior:'smooth'})}
$('analyze').onclick=analyze;$('reset').onclick=()=>{location.reload()};$('toggleSkills').onclick=()=>{let s=$('skills');s.hidden=!s.hidden;$('toggleSkills').textContent=s.hidden?'Show details':'Hide details'};$('lang').onclick=()=>{lang=lang==='en'?'ar':'en';document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.lang=lang;$('lang').textContent=lang==='en'?'العربية':'English';$('introText').textContent=lang==='ar'?ar.introText:'Analysis of all Generation 1–7 heroes using their actual skills, expedition effects, stats and exclusive gear.'};