const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let DB,activeTree='development',activeFilter='all',activeTech=null,lang=localStorage.getItem('saifks-lang')||'ar',plan=[];
const I18N={ar:{title:'مخطط البحوث',subtitle:'استعرض جميع الأبحاث، اختر مستواك الحالي والهدف، وأنشئ خطة كاملة بالموارد والوقت والقوة.',researches:'بحث',levels:'مستوى',trees:'أشجار',allResearch:'جميع الأبحاث',planner:'الخطة',planTitle:'خطة البحث',clear:'مسح',emptyPlanTitle:'لم تضف أبحاثًا بعد',emptyPlanText:'افتح أي بحث وحدد المستوى الحالي والهدف، ثم أضفه إلى الخطة.',time:'الوقت',power:'القوة',bread:'الخبز',wood:'الخشب',stone:'الحجر',iron:'الحديد',gold:'الذهب',copySummary:'نسخ الملخص',currentLevel:'المستوى الحالي',targetLevel:'المستوى المستهدف',addToPlan:'إضافة إلى الخطة',all:'الكل',general:'عام',healing:'العلاج',construction:'البناء',research:'سرعة البحث',training:'التدريب',breadCat:'الخبز',woodCat:'الخشب',stoneCat:'الحجر',ironCat:'الحديد',gathering:'الجمع',infantry:'المشاة',cavalry:'الفرسان',archer:'الرماة',attack:'الهجوم',defense:'الدفاع',health:'الصحة',lethality:'الفتك',march:'المسيرة',max:'أقصى مستوى',results:'نتيجة',notResearched:'غير مطور',level:'المستوى',effect:'التأثير',needs:'المتطلبات',added:'تمت الإضافة',copied:'تم النسخ',incomplete:'بيانات المستويات غير متوفرة في المصدر'},en:{title:'Research Planner',subtitle:'Browse every research, select your current and target levels, and build a complete plan with resources, time, and power.',researches:'Researches',levels:'Levels',trees:'Trees',allResearch:'All Research',planner:'Planner',planTitle:'Research Plan',clear:'Clear',emptyPlanTitle:'No research added yet',emptyPlanText:'Open any research, choose current and target levels, then add it to your plan.',time:'Time',power:'Power',bread:'Bread',wood:'Wood',stone:'Stone',iron:'Iron',gold:'Gold',copySummary:'Copy Summary',currentLevel:'Current Level',targetLevel:'Target Level',addToPlan:'Add to Plan',all:'All',general:'General',healing:'Healing',construction:'Construction',research:'Research Speed',training:'Training',breadCat:'Bread',woodCat:'Wood',stoneCat:'Stone',ironCat:'Iron',gathering:'Gathering',infantry:'Infantry',cavalry:'Cavalry',archer:'Archer',attack:'Attack',defense:'Defense',health:'Health',lethality:'Lethality',march:'March',max:'Max Level',results:'result',notResearched:'Not researched',level:'Level',effect:'Effect',needs:'Requirements',added:'Added',copied:'Copied',incomplete:'Level data is unavailable in the source'}};
const t=k=>I18N[lang][k]||k;
const tree=()=>DB.trees.find(x=>x.id===activeTree);
const techById=id=>DB.trees.flatMap(x=>x.techs).find(x=>x.id===id);
const iconFor=c=>({healing:'✚',construction:'⌂',research:'⌁',training:'⚒',bread:'♨',wood:'♣',stone:'◆',iron:'⚙',gathering:'↗',infantry:'♜',cavalry:'♞',archer:'➶',attack:'⚔',defense:'⬟',health:'♥',lethality:'✦',march:'➜',general:'◎'})[c]||'◎';
function fmt(n){return new Intl.NumberFormat(lang==='ar'?'ar-AE':'en-AE',{notation:n>=1e6?'compact':'standard',maximumFractionDigits:1}).format(Math.round(n||0))}
function fmtTime(s){s=Math.max(0,Math.round(s||0));let d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),p=[];if(d)p.push(`${d}${lang==='ar'?'ي':'d'}`);if(h)p.push(`${h}${lang==='ar'?'س':'h'}`);if(m||!p.length)p.push(`${m}${lang==='ar'?'د':'m'}`);return p.join(' ')}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#langBtn').textContent=lang==='ar'?'EN':'عربي';$('#searchInput').placeholder=$('#searchInput').dataset[`placeholder${lang==='ar'?'Ar':'En'}`];localStorage.setItem('saifks-lang',lang);renderAll()}
function renderTrees(){const colors={development:'var(--blue)',economy:'var(--green)',battle:'var(--red)'};$('#treeTabs').innerHTML=DB.trees.map(x=>`<button class="tree-tab ${x.id===activeTree?'active':''}" style="--tree:${colors[x.id]}" data-tree="${x.id}"><b>${x.name[lang]}</b><span>${x.techs.length} ${t('researches')} · ${x.techs.reduce((a,b)=>a+b.levels.length,0)} ${t('levels')}</span></button>`).join('');$$('.tree-tab').forEach(b=>b.onclick=()=>{activeTree=b.dataset.tree;activeFilter='all';renderAll()})}
function categories(){return ['all',...new Set(tree().techs.map(x=>x.category))]}
function labelCategory(c){if(c==='bread')return t('breadCat');if(c==='wood')return t('woodCat');if(c==='stone')return t('stoneCat');if(c==='iron')return t('ironCat');return t(c)}
function renderFilters(){$('#filters').innerHTML=categories().map(c=>`<button class="filter-btn ${c===activeFilter?'active':''}" data-filter="${c}">${labelCategory(c)}</button>`).join('');$$('.filter-btn').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;renderResearch()})}
function filtered(){const q=$('#searchInput').value.trim().toLowerCase();return tree().techs.filter(x=>(activeFilter==='all'||x.category===activeFilter)&&(!q||`${x.name} ${x.description} ${x.effectRange}`.toLowerCase().includes(q)))}
function renderResearch(){const colors={development:'var(--blue)',economy:'var(--green)',battle:'var(--red)'},items=filtered();$('#activeTreeLabel').textContent=tree().name[lang];$('#resultCount').textContent=`${items.length} ${t('results')}`;$('#researchGrid').innerHTML=items.length?items.map(x=>`<article class="research-card" style="--tree:${colors[activeTree]}" data-tech="${x.id}"><div class="tech-card-head"><div class="tech-icon">${iconFor(x.category)}</div><span class="max-badge">${t('max')} ${x.maxLevel}</span></div><h3>${x.name}</h3><p>${x.description||'—'}</p><div class="effect-line">${x.effectRange||(!x.dataComplete?t('incomplete'):'—')}</div></article>`).join(''):`<div class="no-results">${lang==='ar'?'لا توجد نتائج مطابقة':'No matching results'}</div>`;$$('.research-card').forEach(c=>c.onclick=()=>openModal(c.dataset.tech))}
function openModal(id){activeTech=techById(id);const colors={development:'var(--blue)',economy:'var(--green)',battle:'var(--red)'},parent=DB.trees.find(x=>x.techs.some(y=>y.id===id));$('.modal-card').style.setProperty('--tree',colors[parent.id]);$('#modalIcon').textContent=iconFor(activeTech.category);$('#modalTree').textContent=parent.name[lang];$('#modalTitle').textContent=activeTech.name;$('#modalDesc').textContent=activeTech.description||'—';$('#modalRange').textContent=activeTech.effectRange||(!activeTech.dataComplete?t('incomplete'):'—');const cur=$('#currentLevel'),tar=$('#targetLevel');cur.innerHTML='';for(let i=0;i<activeTech.maxLevel;i++)cur.add(new Option(i===0?`0 — ${t('notResearched')}`:i,i));cur.value='0';renderTarget();$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function renderTarget(){const c=Number($('#currentLevel').value),tar=$('#targetLevel');tar.innerHTML='';for(let i=c+1;i<=activeTech.maxLevel;i++)tar.add(new Option(i,i));tar.value=String(activeTech.maxLevel);renderModalCalc()}
function selectedLevels(){if(!activeTech)return[];let c=Number($('#currentLevel').value),tar=Number($('#targetLevel').value);return activeTech.levels.filter(x=>x.level>c&&x.level<=tar)}
function totals(rows){const z={time:0,power:0,bread:0,wood:0,stone:0,iron:0,gold:0};rows.forEach(r=>{z.time+=r.timeSeconds||0;z.power+=r.power||0;Object.keys(r.cost||{}).forEach(k=>z[k]=(z[k]||0)+(r.cost[k]||0))});return z}
function renderModalCalc(){const rows=selectedLevels(),z=totals(rows);$('#modalTotals').innerHTML=[['time',fmtTime(z.time)],['power',fmt(z.power)],['bread',fmt(z.bread)],['wood',fmt(z.wood)],['stone',fmt(z.stone)],['iron',fmt(z.iron)],['gold',fmt(z.gold)]].map(([k,v])=>`<div class="modal-total"><small>${t(k)}</small><b>${v}</b></div>`).join('');$('#levelDetails').innerHTML=rows.length?rows.map(r=>`<div class="level-row"><div class="level-row-head"><b>${t('level')} ${r.level}</b><b>+${fmt(r.power)} ${t('power')}</b></div><div class="level-row-grid"><span>${t('time')}: ${r.timeText}</span><span>${t('effect')}: ${r.effect}</span><span>${t('needs')}: ${r.needs}</span></div></div>`).join(''):`<div class="no-results">${t('incomplete')}</div>`}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
function addPlan(){if(!activeTech)return;let c=Number($('#currentLevel').value),tar=Number($('#targetLevel').value);const entry={id:activeTech.id,current:c,target:tar};const idx=plan.findIndex(x=>x.id===entry.id);idx>=0?plan[idx]=entry:plan.push(entry);savePlan();renderPlan();closeModal()}
function planRows(item){const tech=techById(item.id);return tech.levels.filter(x=>x.level>item.current&&x.level<=item.target)}
function renderPlan(){const container=$('#planItems');container.innerHTML=plan.map((p,i)=>{const tech=techById(p.id);return `<div class="plan-item"><div class="plan-item-head"><div><b>${tech.name}</b><small>${p.current} → ${p.target}</small></div><button data-remove="${i}">×</button></div></div>`}).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{plan.splice(Number(b.dataset.remove),1);savePlan();renderPlan()});$('#emptyPlan').classList.toggle('hidden',plan.length>0);$('#summary').classList.toggle('hidden',plan.length===0);const z=totals(plan.flatMap(planRows));$('#sumTime').textContent=fmtTime(z.time);$('#sumPower').textContent=fmt(z.power);$('#sumBread').textContent=fmt(z.bread);$('#sumWood').textContent=fmt(z.wood);$('#sumStone').textContent=fmt(z.stone);$('#sumIron').textContent=fmt(z.iron);$('#sumGold').textContent=fmt(z.gold)}
function savePlan(){localStorage.setItem('saifks-research-plan-phase1',JSON.stringify(plan))}
function copySummary(){const z=totals(plan.flatMap(planRows));const lines=[`SaifKS Research Plan`,``,...plan.map(p=>`${techById(p.id).name}: ${p.current} → ${p.target}`),``,`${t('time')}: ${fmtTime(z.time)}`,`${t('power')}: ${fmt(z.power)}`,`${t('bread')}: ${fmt(z.bread)}`,`${t('wood')}: ${fmt(z.wood)}`,`${t('stone')}: ${fmt(z.stone)}`,`${t('iron')}: ${fmt(z.iron)}`,`${t('gold')}: ${fmt(z.gold)}`];navigator.clipboard.writeText(lines.join('\n')).then(()=>{const b=$('#copySummary'),old=b.textContent;b.textContent=t('copied');setTimeout(()=>b.textContent=old,1200)})}
function renderAll(){renderTrees();renderFilters();renderResearch();renderPlan()}
fetch('research-data.json').then(r=>r.json()).then(data=>{DB=data;try{plan=JSON.parse(localStorage.getItem('saifks-research-plan-phase1')||'[]')}catch{plan=[]}$('#techCount').textContent=DB.meta.parsedTotals.technologies;$('#levelCount').textContent=DB.meta.parsedTotals.levels;applyLang()});
$('#searchInput').addEventListener('input',renderResearch);$('#langBtn').onclick=()=>{lang=lang==='ar'?'en':'ar';applyLang()};$('#homeBtn').onclick=()=>location.href='/';$('#currentLevel').onchange=renderTarget;$('#targetLevel').onchange=renderModalCalc;$('#addToPlan').onclick=addPlan;$$('[data-close-modal]').forEach(x=>x.onclick=closeModal);$('#clearPlan').onclick=()=>{plan=[];savePlan();renderPlan()};$('#copySummary').onclick=copySummary;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
