// Translations that complement the original research dataset labels.
window.RESEARCH_EXTRA_TRANSLATIONS = {
  names: {
    fr: ["Bandages","Extension du camp","Outils d'entraînement","Amélioration des outils","Outillage","Extension de l'infirmerie","Tactiques de commandement","Production de pain","Production de bois","Production de pierre","Production de fer","Collecte de pain","Collecte de bois","Collecte de pierre","Extraction de fer","Préparation des armes","Tactiques de riposte","Visée de précision","Charge de cavalerie","Formations défensives","Lignes de garde","Formations de rempart","Entraînement défensif spécial","Techniques de survie","Techniques d'assaut","Extension du régiment","Combat rapproché","Tir ciblé","Amélioration des lances","Amélioration des boucliers","Travail du cuir","Cotte de mailles renforcée"],
    es: ["Vendajes","Ampliación del campamento","Herramientas de entrenamiento","Mejora de herramientas","Preparación de herramientas","Ampliación de la enfermería","Tácticas de mando","Producción de pan","Producción de madera","Producción de piedra","Producción de hierro","Recolección de pan","Recolección de madera","Recolección de piedra","Extracción de hierro","Preparación de armas","Tácticas de represalia","Puntería de precisión","Carga de caballería","Formaciones defensivas","Líneas de guardia","Formaciones de baluarte","Entrenamiento defensivo especial","Técnicas de supervivencia","Técnicas de asalto","Ampliación del regimiento","Combate cuerpo a cuerpo","Tiro dirigido","Mejora de lanzas","Mejora de escudos","Marroquinería","Cota de malla reforzada"],
    de: ["Verbände","Lagererweiterung","Trainingswerkzeuge","Werkzeugverbesserung","Ausrüstung","Lazaretterweiterung","Führungstaktik","Brotproduktion","Holzproduktion","Steinproduktion","Eisenproduktion","Brotsammeln","Holzsammeln","Steinsammeln","Eisenabbau","Waffenvorbereitung","Vergeltungstaktik","Präzisionszielung","Kavallerieangriff","Verteidigungsformationen","Wachlinien","Bollwerkformationen","Spezielles Verteidigungstraining","Überlebenstechniken","Angriffstechniken","Regimentserweiterung","Nahkampf","Gezieltes Schießen","Lanzenverbesserung","Schildverbesserung","Lederverarbeitung","Verstärktes Kettenhemd"]
  },
  stats: {
    fr: ["Vitesse de soin","Capacité d'entraînement","Vitesse d'entraînement","Vitesse de recherche","Vitesse de construction","Capacité de l'infirmerie","File de marche","Production de pain","Production de bois","Production de pierre","Production de fer","Vitesse de collecte du pain","Vitesse de collecte du bois","Vitesse de collecte de pierre","Vitesse d'extraction du fer","Attaque de l'infanterie","Défense de l'infanterie","Létalité de l'infanterie","Santé de l'infanterie","Attaque des archers","Défense des archers","Létalité des archers","Santé des archers","Attaque de la cavalerie","Défense de la cavalerie","Létalité de la cavalerie","Santé de la cavalerie","Attaque des troupes","Défense des troupes","Santé des troupes","Létalité des troupes","Capacité de marche"],
    es: ["Velocidad de curación","Capacidad de entrenamiento","Velocidad de entrenamiento","Velocidad de investigación","Velocidad de construcción","Capacidad de la enfermería","Cola de marcha","Producción de pan","Producción de madera","Producción de piedra","Producción de hierro","Velocidad de recolección de pan","Velocidad de recolección de madera","Velocidad de recolección de piedra","Velocidad de extracción de hierro","Ataque de infantería","Defensa de infantería","Letalidad de infantería","Salud de infantería","Ataque de arqueros","Defensa de arqueros","Letalidad de arqueros","Salud de arqueros","Ataque de caballería","Defensa de caballería","Letalidad de caballería","Salud de caballería","Ataque de tropas","Defensa de tropas","Salud de tropas","Letalidad de tropas","Capacidad de marcha"],
    de: ["Heilgeschwindigkeit","Trainingskapazität","Trainingsgeschwindigkeit","Forschungsgeschwindigkeit","Baugeschwindigkeit","Lazarettkapazität","Marschwarteschlange","Brotproduktion","Holzproduktion","Steinproduktion","Eisenproduktion","Brotsammelgeschwindigkeit","Holzsammelgeschwindigkeit","Steinsammelgeschwindigkeit","Eisenabbaugeschwindigkeit","Infanterieangriff","Infanterieverteidigung","Infanterietödlichkeit","Infanteriegesundheit","Bogenschützenangriff","Bogenschützenverteidigung","Bogenschützentödlichkeit","Bogenschützengesundheit","Kavallerieangriff","Kavallerieverteidigung","Kavallerietödlichkeit","Kavalleriegesundheit","Truppenangriff","Truppenverteidigung","Truppengesundheit","Truppentödlichkeit","Marschkapazität"]
  },
  legend: {
    en: ["Not researched","Researched","In plan","Current level","Target level","Save levels only"],
    ar: ["غير مطور","مطور","داخل الخطة","المستوى الحالي","المستوى المستهدف","حفظ المستويات فقط"],
    fr: ["Non recherché","Recherché","Dans le plan","Niveau actuel","Niveau cible","Enregistrer les niveaux"],
    es: ["Sin investigar","Investigado","En el plan","Nivel actual","Nivel objetivo","Guardar niveles"],
    de: ["Nicht erforscht","Erforscht","Im Plan","Aktuelle Stufe","Zielstufe","Stufen speichern"],
    tr: ["Araştırılmadı","Araştırıldı","Planda","Mevcut seviye","Hedef seviye","Seviyeleri kaydet"],
    ko: ["미연구","연구 완료","계획에 포함","현재 레벨","목표 레벨","레벨만 저장"],
    ja: ["未研究","研究済み","計画中","現在のレベル","目標レベル","レベルのみ保存"],
    zh: ["未研究","已研究","计划中","当前等级","目标等级","仅保存等级"]
  },
  detail: {
    en: ["Bonus increase","Upgrade time","Power","Levels","Academy level","Target level requirements","No requirements recorded for this level.","Update research in plan","Add to plan","Your selection is saved automatically","Current and target levels saved","Plan updated","Levels saved","and","Built by Saif"],
    ar: ["زيادة المكافأة","وقت الترقية","القوة","عدد المستويات","مستوى الأكاديمية","متطلبات المستوى المستهدف","لا توجد متطلبات مسجلة لهذا المستوى.","تحديث البحث في الخطة","إضافة إلى الخطة","يتم حفظ الاختيار تلقائيًا","تم تثبيت المستوى الحالي والمستهدف","تم تحديث الخطة","تم حفظ المستويات","و","صنعه سيف"],
    fr: ["Gain de bonus","Temps d'amélioration","Puissance","Niveaux","Niveau de l'académie","Conditions du niveau cible","Aucune condition indiquée pour ce niveau.","Mettre à jour la recherche","Ajouter au plan","Sélection enregistrée automatiquement","Niveaux actuel et cible enregistrés","Plan mis à jour","Niveaux enregistrés","et","Créé par Saif"],
    es: ["Aumento de bonificación","Tiempo de mejora","Poder","Niveles","Nivel de academia","Requisitos del nivel objetivo","No hay requisitos registrados para este nivel.","Actualizar investigación","Añadir al plan","Selección guardada automáticamente","Niveles actual y objetivo guardados","Plan actualizado","Niveles guardados","y","Creado por Saif"],
    de: ["Bonuszuwachs","Verbesserungszeit","Macht","Stufen","Akademiestufe","Voraussetzungen der Zielstufe","Für diese Stufe sind keine Voraussetzungen verzeichnet.","Forschung im Plan aktualisieren","Zum Plan hinzufügen","Auswahl wird automatisch gespeichert","Aktuelle und Zielstufe gespeichert","Plan aktualisiert","Stufen gespeichert","und","Erstellt von Saif"],
    tr: ["Bonus artışı","Yükseltme süresi","Güç","Seviyeler","Akademi seviyesi","Hedef seviye gereksinimleri","Bu seviye için gereksinim kaydedilmemiş.","Araştırmayı planda güncelle","Plana ekle","Seçim otomatik kaydedilir","Mevcut ve hedef seviye kaydedildi","Plan güncellendi","Seviyeler kaydedildi","ve","Saif tarafından yapıldı"],
    ko: ["효과 증가","업그레이드 시간","전투력","레벨","아카데미 레벨","목표 레벨 요구 조건","이 레벨의 기록된 요구 조건이 없습니다.","계획의 연구 업데이트","계획에 추가","선택 사항이 자동 저장됩니다","현재 및 목표 레벨 저장됨","계획 업데이트됨","레벨 저장됨","및","Saif 제작"],
    ja: ["効果の増加","強化時間","戦力","レベル","学院レベル","目標レベルの条件","このレベルの条件は登録されていません。","計画の研究を更新","計画に追加","選択は自動保存されます","現在と目標のレベルを保存しました","計画を更新しました","レベルを保存しました","と","Saif 制作"],
    zh: ["增益提升","升级时间","战力","等级","学院等级","目标等级要求","此等级没有记录要求。","更新计划中的研究","加入计划","选择会自动保存","已保存当前和目标等级","计划已更新","等级已保存","和","Saif 制作"]
  }
};
